### ISSUE TITLE
Add the ability to view/download a full list of contributors

### ISSUE THREAD

**Issue by audinowho** [PMDCollab/SpriteViewer#1]
For a dev planning on using certain sprites, it would be convenient for them to have an easy download to the contributors list of a specific sprite to meet credit requirements.  SpriteCollab currently has a txt of the full history of contributors, so that can be sent to them.

**Comment by 25Pi25** [comment]
solved with https://github.com/PMDCollab/PMD-collab-wiki/pull/95, this can probably just be closed after the pr is merged
