### ISSUE TITLE
Add option to Filter/Sort by Contributor and status

### ISSUE THREAD

**Issue by audinowho** [PMDCollab/SpriteViewer#2]
Common use cases are:
-Aspiring contributor wants to see all the pokemon that don't have portraits, and which ones need help being worked on.
-Reviewer can see the full list of incomplete portraits and make sure the ones that are high quality are marked as "exists".
-User may want to see all sprites made by chunsoft, or a specific user.  If god forbid some user uploaded sprites that were actually stolen from somewhere else, they can be quickly searched up.

**Comment by theDasK** [comment]
Implemented on lastes pull
